import { JobPortal } from '@prisma/client';
import { PortalDefinition } from '../types/verification.types';

/**
 * Strict portal definitions — hostname anchored regex prevents evil-*.com bypass
 * Path patterns are confirmation/success pages only
 * v1.1 Universal ATS Intelligence — expanded to 20+ ATS platforms
 */

export const SUPPORTED_PORTALS: PortalDefinition[] = [
  {
    portal: 'GREENHOUSE' as JobPortal,
    displayName: 'Greenhouse',
    hostPatterns: [
      /(?:^|\.)greenhouse\.io$/,
      /(?:^|\.)greenhouse\.com$/,
      /^boards\.greenhouse\.io$/,
      /(?:^|\.)job-boards\.greenhouse\.io$/,
    ],
    pathPatterns: [
      /\/confirmation/i,
      /\/applications?\/.*submitted/i,
      /\/thank.?you/i,
      /\/success/i,
      /\/applied/i,
      /\/submitted/i,
    ],
    titlePatterns: [
      /application submitted/i,
      /thank you/i,
      /confirmation/i,
      /your application/i,
      /success/i,
      /all done/i,
      /you're all set/i,
    ],
    headingPatterns: [
      /application submitted/i,
      /thank you for applying/i,
      /your application has been submitted/i,
      /application received/i,
      /success/i,
      /all done/i,
      /you're all set/i,
    ],
    confirmationPatterns: [
      /your application for .* has been submitted/i,
      /thank you for applying/i,
      /application submitted/i,
      /we have received your application/i,
      /all done/i,
      /you're all set/i,
      /we will review/i,
      /reference number/i,
    ],
    referencePatterns: [
      /application\s*(id|reference|number)\s*[:#]?\s*([A-Z0-9-]{6,})/i,
      /reference\s*number\s*[:#]?\s*([A-Z0-9-]+)/i,
    ],
    expectedSelectors: [
      '#application_confirmation',
      '.application-submitted',
      '.thank-you',
      '[class*="confirmation"]',
      '[data-mapped="true"]',
      '.success-card',
    ],
    applyButtonSelectors: ['a[href*="apply"]', 'button'],
    weightBonus: 5,
  },
  {
    portal: 'LEVER' as JobPortal,
    displayName: 'Lever',
    hostPatterns: [
      /(?:^|\.)lever\.co$/,
      /^jobs\.lever\.co$/,
    ],
    pathPatterns: [
      /\/applied/i,
      /\/application.*success/i,
      /\/confirmation/i,
      /\/thank.?you/i,
      /\/success/i,
    ],
    titlePatterns: [
      /you have applied/i,
      /application submitted/i,
      /thank you/i,
      /success/i,
    ],
    headingPatterns: [
      /you have applied/i,
      /application submitted/i,
      /thank you/i,
      /all done/i,
    ],
    confirmationPatterns: [
      /you have applied to/i,
      /application submitted/i,
      /thank you for applying/i,
      /all done/i,
    ],
    referencePatterns: [
      /reference\s*[:#]?\s*([A-Z0-9-]+)/i,
    ],
    expectedSelectors: [
      '.application-complete',
      '.posting-apply-success',
      '[class*="success"]',
    ],
    applyButtonSelectors: ['button.posting-btn-submit'],
    weightBonus: 5,
  },
  {
    portal: 'LINKEDIN' as JobPortal,
    displayName: 'LinkedIn',
    hostPatterns: [
      /(?:^|\.)linkedin\.com$/,
    ],
    pathPatterns: [
      /\/jobs\/.*\/applied/i,
      /\/easy-apply/i,
      /\/application.*submitted/i,
      /\/confirmation/i,
      /\/applied/i,
    ],
    titlePatterns: [
      /application submitted/i,
      /your application was sent/i,
      /applied/i,
      /success/i,
    ],
    headingPatterns: [
      /application submitted/i,
      /your application was sent to/i,
      /applied/i,
      /you applied/i,
    ],
    confirmationPatterns: [
      /your application was sent/i,
      /application submitted/i,
      /you applied/i,
    ],
    referencePatterns: [],
    expectedSelectors: [
      '.artdeco-inline-feedback--success',
      '[data-test-modal*="success"]',
      'h2[class*="success"]',
    ],
    applyButtonSelectors: ['button[aria-label*="Apply"]', 'button.jobs-apply-button'],
    weightBonus: 5,
  },
  {
    portal: 'INDEED' as JobPortal,
    displayName: 'Indeed',
    hostPatterns: [/(?:^|\.)indeed\.com$/, /(?:^|\.)indeed\.[a-z.]+$/],
    pathPatterns: [/\/applied/i, /\/application.*complete/i, /\/confirmation/i, /\/success/i],
    titlePatterns: [/applied/i, /application submitted/i, /success/i, /thank you/i],
    headingPatterns: [/you applied/i, /application submitted/i, /thank you/i],
    confirmationPatterns: [/you applied to/i, /application submitted/i, /thank you/i],
    referencePatterns: [],
    expectedSelectors: ['[class*="applied"]', '.jobsearch-IndeedApplyButton--applied'],
    applyButtonSelectors: ['button[aria-label*="Apply"]'],
    weightBonus: 3,
  },
  {
    portal: 'WORKDAY' as JobPortal,
    displayName: 'Workday',
    hostPatterns: [
      /(?:^|\.)myworkdayjobs\.com$/,
      /(?:^|\.)myworkday\.com$/,
      /(?:^|\.)workday\.com$/,
    ],
    pathPatterns: [
      /\/confirmation/i,
      /\/submitted/i,
      /\/application.*complete/i,
      /\/thank.*you/i,
      /\/success/i,
    ],
    titlePatterns: [
      /submission successful/i,
      /you have successfully submitted/i,
      /your application/i,
      /thank you/i,
      /success/i,
    ],
    headingPatterns: [
      /you have successfully submitted/i,
      /application submitted/i,
      /submission successful/i,
      /thank you for applying/i,
      /all done/i,
    ],
    confirmationPatterns: [
      /you have successfully submitted/i,
      /your application has been submitted/i,
      /thank you for applying/i,
      /application.*submitted/i,
      /all done/i,
    ],
    referencePatterns: [
      /application\s*id\s*[:#]?\s*([A-Z0-9-]+)/i,
      /reference\s*number\s*[:#]?\s*([A-Z0-9-]+)/i,
      /submission\s*id\s*[:#]?\s*([A-Z0-9-]+)/i,
    ],
    expectedSelectors: [
      '[data-automation-id="confirmationPage"]',
      '[data-automation-id="candidateApplicationConfirmation"]',
      '[data-automation-id="applicationConfirmation"]',
      'section[data-automation-id*="confirmation"]',
    ],
    applyButtonSelectors: ['[data-automation-id*="apply"]'],
    weightBonus: 10,
  },
  // ── New v1.1 Universal ATS ───────────────────────────────────────────
  {
    portal: 'RECRUITEE' as JobPortal,
    displayName: 'Recruitee',
    hostPatterns: [/(?:^|\.)recruitee\.com$/],
    pathPatterns: [/\/applied/i, /\/confirmation/i, /\/thank-you/i, /\/success/i, /\/applied/i],
    titlePatterns: [/applied/i, /thank you/i, /success/i, /all done/i],
    headingPatterns: [/all done/i, /thank you/i, /applied/i, /you're all set/i],
    confirmationPatterns: [/all done/i, /thank you/i, /applied/i, /you're all set/i, /we have received/i],
    referencePatterns: [/application\s*id\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="confirmation"]', '.application--confirmation', '[data-mapped="true"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'ASHBY' as JobPortal,
    displayName: 'Ashby',
    hostPatterns: [/(?:^|\.)ashbyhq\.com$/],
    pathPatterns: [/\/application/i, /\/confirmation/i, /\/submitted/i, /\/success/i],
    titlePatterns: [/application submitted/i, /thank you/i, /applied/i],
    headingPatterns: [/thank you/i, /application submitted/i, /all done/i],
    confirmationPatterns: [/thank you/i, /application submitted/i, /all done/i],
    referencePatterns: [/application\s*id\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[data-ashby-form]', '.ashby-application--confirmation'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'TEAMTAILOR' as JobPortal,
    displayName: 'Teamtailor',
    hostPatterns: [/(?:^|\.)teamtailor\.com$/],
    pathPatterns: [/\/applications/i, /\/confirmation/i, /\/thank-you/i, /\/applied/i],
    titlePatterns: [/thank you/i, /application submitted/i],
    headingPatterns: [/thank you for applying/i, /application submitted/i],
    confirmationPatterns: [/thank you for applying/i, /your application has been submitted/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="teamtailor"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'SMARTRECRUITERS' as JobPortal,
    displayName: 'SmartRecruiters',
    hostPatterns: [/(?:^|\.)smartrecruiters\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/success/i],
    titlePatterns: [/thank you/i, /application submitted/i],
    headingPatterns: [/thank you/i, /application submitted/i],
    confirmationPatterns: [/thank you/i, /we have received your application/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['.sr-apply-button', '[class*="smartRecruiters"]'],
    applyButtonSelectors: ['.sr-apply-button'],
    weightBonus: 5,
  },
  {
    portal: 'BAMBOOHR' as JobPortal,
    displayName: 'BambooHR',
    hostPatterns: [/(?:^|\.)bamboohr\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/success/i],
    titlePatterns: [/thank you/i, /application submitted/i],
    headingPatterns: [/thank you/i, /application submitted/i],
    confirmationPatterns: [/thank you/i, /your application has been submitted/i],
    referencePatterns: [/application\s*id\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[id*="bamboohr"]', '[class*="bamboohr"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'JOBVITE' as JobPortal,
    displayName: 'Jobvite',
    hostPatterns: [/(?:^|\.)jobvite\.com$/],
    pathPatterns: [/\/confirmation/i, /\/complete/i, /\/thank-you/i, /\/applied/i],
    titlePatterns: [/thank you/i, /application submitted/i, /confirmation/i],
    headingPatterns: [/thank you/i, /application submitted/i],
    confirmationPatterns: [/thank you/i, /your application has been submitted/i],
    referencePatterns: [/requisition\s*id\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="jv-confirmation"]', '.jv-confirmation'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'PERSONIO' as JobPortal,
    displayName: 'Personio',
    hostPatterns: [/(?:^|\.)personio\.com$/, /(?:^|\.)personio\.de$/],
    pathPatterns: [/\/confirmation/i, /\/success/i, /\/applied/i],
    titlePatterns: [/thank you/i, /application received/i, /success/i],
    headingPatterns: [/thank you for your application/i, /application received/i],
    confirmationPatterns: [/thank you for your application/i, /we have received your application/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="personio"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'ICIMS' as JobPortal,
    displayName: 'iCIMS',
    hostPatterns: [/(?:^|\.)icims\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/success/i, /\/thank-you/i],
    titlePatterns: [/thank you/i, /application submitted/i, /confirmation/i],
    headingPatterns: [/thank you/i, /your application has been submitted/i],
    confirmationPatterns: [/thank you/i, /your application has been submitted/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="iCIMS"]', '[id*="iCIMS"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'JAZZHR' as JobPortal,
    displayName: 'JazzHR',
    hostPatterns: [/(?:^|\.)jazzhr\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/thank-you/i],
    titlePatterns: [/thank you/i, /application submitted/i],
    headingPatterns: [/thank you/i, /application submitted/i],
    confirmationPatterns: [/thank you for applying/i, /your application has been submitted/i],
    referencePatterns: [/application\s*id\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="jazzhr"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'BREEZYHR' as JobPortal,
    displayName: 'BreezyHR',
    hostPatterns: [/(?:^|\.)breezy\.hr$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/thank-you/i],
    titlePatterns: [/thank you/i, /application submitted/i, /applied/i],
    headingPatterns: [/thank you/i, /you have applied/i],
    confirmationPatterns: [/thank you/i, /your application has been submitted/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="breezy"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'COMEET' as JobPortal,
    displayName: 'Comeet',
    hostPatterns: [/(?:^|\.)comeet\.co$/, /(?:^|\.)comeet\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/success/i],
    titlePatterns: [/thank you/i, /application submitted/i],
    headingPatterns: [/thank you/i, /application submitted/i],
    confirmationPatterns: [/thank you for applying/i, /your application has been submitted/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="comeet"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'FOUNTAIN' as JobPortal,
    displayName: 'Fountain',
    hostPatterns: [/(?:^|\.)fountain\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/success/i, /\/thank-you/i],
    titlePatterns: [/thank you/i, /application submitted/i, /all done/i],
    headingPatterns: [/all done/i, /thank you/i, /you're all set/i],
    confirmationPatterns: [/all done/i, /thank you/i, /you're all set/i],
    referencePatterns: [/application\s*id\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="fountain"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'PINPOINT' as JobPortal,
    displayName: 'Pinpoint',
    hostPatterns: [/(?:^|\.)pinpointhq\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/thank-you/i],
    titlePatterns: [/thank you/i, /application submitted/i],
    headingPatterns: [/thank you/i, /application submitted/i],
    confirmationPatterns: [/thank you for applying/i, /your application has been submitted/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="pinpoint"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'RIPPLING' as JobPortal,
    displayName: 'Rippling ATS',
    hostPatterns: [/(?:^|\.)rippling\.com$/, /(?:^|\.)ats\.rippling\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/success/i],
    titlePatterns: [/thank you/i, /application submitted/i, /all done/i],
    headingPatterns: [/all done/i, /thank you/i, /you're all set/i],
    confirmationPatterns: [/all done/i, /thank you/i, /you're all set/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="rippling"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'WORKABLE' as JobPortal,
    displayName: 'Workable',
    hostPatterns: [/(?:^|\.)workable\.com$/, /(?:^|\.)jobs\.workable\.com$/],
    pathPatterns: [/\/confirmation/i, /\/applied/i, /\/thank-you/i, /\/success/i],
    titlePatterns: [/thank you/i, /application submitted/i],
    headingPatterns: [/thank you for applying/i, /application submitted/i],
    confirmationPatterns: [/thank you for applying/i, /your application has been submitted/i],
    referencePatterns: [/reference\s*[:#]?\s*([A-Z0-9-]+)/i],
    expectedSelectors: ['[class*="workable"]', '[class*="confirmation"]'],
    applyButtonSelectors: ['button'],
    weightBonus: 5,
  },
  {
    portal: 'ZIPRECRUITER' as JobPortal,
    displayName: 'ZipRecruiter',
    hostPatterns: [/(?:^|\.)ziprecruiter\.com$/],
    pathPatterns: [/\/applied/i, /\/confirmation/i, /\/thank.?you/i],
    titlePatterns: [/applied/i, /application sent/i, /thank you/i],
    headingPatterns: [/application sent/i, /applied/i, /thank you/i],
    confirmationPatterns: [/application sent/i, /you applied/i, /thank you/i],
    referencePatterns: [],
    expectedSelectors: ['.job-applied', '[class*="applied"]'],
    applyButtonSelectors: ['button.apply-button'],
    weightBonus: 3,
  },
  {
    portal: 'GLASSDOOR' as JobPortal,
    displayName: 'Glassdoor',
    hostPatterns: [/(?:^|\.)glassdoor\.com$/],
    pathPatterns: [/\/Job\/applied/i, /\/applied/i, /\/confirmation/i],
    titlePatterns: [/application submitted/i, /thank you/i],
    headingPatterns: [/application submitted/i, /thank you/i],
    confirmationPatterns: [/application submitted/i, /thank you/i],
    referencePatterns: [],
    expectedSelectors: ['.appliedConfirm', '[data-test*="applied"]'],
    applyButtonSelectors: ['button[data-test*="apply"]'],
    weightBonus: 3,
  },
  {
    portal: 'CAREERBUILDER' as JobPortal,
    displayName: 'CareerBuilder',
    hostPatterns: [/(?:^|\.)careerbuilder\.com$/],
    pathPatterns: [/\/applied/i, /\/confirmation/i],
    titlePatterns: [/applied/i, /thank you/i],
    headingPatterns: [/applied/i, /thank you/i],
    confirmationPatterns: [/applied/i, /thank you/i],
    referencePatterns: [],
    expectedSelectors: ['[class*="applied"]'],
    applyButtonSelectors: ['button.apply'],
    weightBonus: 2,
  },
  {
    portal: 'WELLFOUND' as JobPortal,
    displayName: 'Wellfound',
    hostPatterns: [/(?:^|\.)wellfound\.com$/, /(?:^|\.)angel\.co$/],
    pathPatterns: [/\/applied/i, /\/confirmation/i],
    titlePatterns: [/applied/i, /thank you/i],
    headingPatterns: [/applied/i, /thank you/i],
    confirmationPatterns: [/applied/i, /thank you/i],
    referencePatterns: [],
    expectedSelectors: [],
    applyButtonSelectors: [],
    weightBonus: 2,
  },
  {
    portal: 'OTHER' as JobPortal,
    displayName: 'Generic Career Site',
    hostPatterns: [
      /careers\./,
      /jobs\./,
    ],
    pathPatterns: [
      /\/confirmation/i,
      /\/thank.?you/i,
      /\/success/i,
      /\/submitted/i,
      /\/applied/i,
      /\/completed/i,
      /\/done/i,
      /\/finish/i,
      /\/receipt/i,
      /\/reference/i,
    ],
    titlePatterns: [
      /thank you/i,
      /application submitted/i,
      /application received/i,
      /success/i,
      /all done/i,
      /you're all set/i,
      /applied/i,
    ],
    headingPatterns: [
      /thank you/i,
      /application submitted/i,
      /application received/i,
      /all done/i,
      /you're all set/i,
      /success/i,
    ],
    confirmationPatterns: [
      /thank you for applying/i,
      /your application has been submitted/i,
      /application received/i,
      /all done/i,
      /you're all set/i,
      /we have received your application/i,
      /we will review/i,
      /reference number/i,
      /we appreciate your interest/i,
      /our team will review/i,
    ],
    referencePatterns: [
      /application\s*(id|reference)?\s*[:#]?\s*([A-Z0-9-]{4,})/i,
    ],
    expectedSelectors: [
      '[class*="confirmation"]',
      '[class*="success"]',
      '.success-card',
      '.confirmation-card',
      '.receipt-card',
      '[data-automation-id*="confirmation"]',
    ],
    applyButtonSelectors: ['button'],
    weightBonus: 2,
  },
];

export const STRICT_SUPPORTED_PORTALS = SUPPORTED_PORTALS.filter(p => p.portal !== 'OTHER');

export const NEGATIVE_KEYWORDS = [
  /error/i,
  /failed/i,
  /submission failed/i,
  /validation failed/i,
  /required field/i,
  /resume missing/i,
  /draft/i,
  /incomplete/i,
  /cancelled/i,
  /unauthorized/i,
  /access denied/i,
  /session expired/i,
];

export const CONFIRMATION_KEYWORDS = [
  'application submitted',
  'application received',
  'application complete',
  'successfully applied',
  'thank you for applying',
  'your application has been submitted',
  'we have received your application',
  'submission successful',
  'you have successfully submitted',
  'all done',
  'you are all set',
  'you\'re all set',
  'success',
  'applied',
  'confirmation',
];
