export const POSITIVE_KEYWORDS = [
  'application submitted',
  'application received',
  'application complete',
  'application completed',
  'application sent',
  'application accepted',
  'application confirmed',
  'successfully applied',
  'applied successfully',
  'submission successful',
  'submission complete',
  'submission confirmed',
  'successfully submitted',
  'your application has been submitted',
  'your application has been received',
  'thank you for applying',
  'thank you',
  "we've received your application",
  'application processed',
  'application recorded',
  'application successful',
  'your submission has been received',
  'application saved',
  'application finished',
  'completed',
  'complete',
  'done',
  'finished',
  'accepted',
  'received',
  'confirmed',
  'submitted',
  'you are all set',
  'thanks for applying'
];

export const NEGATIVE_KEYWORDS = [
  'error',
  'failed',
  'submission failed',
  'validation failed',
  'required field',
  'resume missing',
  'continue application',
  'draft',
  'incomplete',
  'cancelled',
  'retry',
  'try again',
  'upload resume',
  'upload required',
  'session expired',
  'unauthorized',
  'access denied'
];

export const URL_PATTERNS = [
  'submitted',
  'confirmation',
  'success',
  'completed',
  'complete',
  'thank-you',
  'thankyou',
  'receipt',
  'status',
  'finished',
  'done',
  'confirmed'
];
